### ISSUE TITLE
Make sure code and models are good

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/wildhellgarden#9]
@dbuona will comment and clean wildtimes_analysis.R. Then @DeirdreLoughnan will make sure it all makes sense and is doing what it should be

**Comment by dbuona** [comment]
@DeirdreLoughnan I just pushed the R script wildtimes_analysis.R with comments. If you can check it that would be lovely. Let me know if you have questions and we can set up a time to zoom if anything is unclear.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan When you are working on this can you set up an ifelse for the setwd *and* can you write out some form of the cleaned data so people like me could possible run some of the code without loading all the packages? I think it could be good actually to divide the current code into some preanalysis cleaning script and cleaning script. Then more of us (er,um, me) could run the models and play with the data.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver @dbuona I have started work on this.

- I created a source code folder that has code that compiles the weather data and code that runs the conceptual figure and other pre-analysis figures. 
-  I saved the compiled weather data in the output folder, gddData.csv, and read it into the wildtimes_analysis code.
- I could further clean the code and move the calculations of the thermal growing season to a source file as well, and another for all the posterior plotting. But the current version should run @lizzieinvancouver without any unusual packages.

@dbuona The only issue in the code I found was with the [creation of cg_wgdd (line 80)](https://github.com/lizzieinvancouver/wildhellgarden/blob/master/analyses/wildtimes_analysis.R), it looked like we were loosing some rows of data using left_join, so I updated the code to merge and specified specific columns and that all rows were true. If this is not correct, we can revert it back to the original.

It was also not clear what the values in the [conceptual figure plotting code](https://github.com/lizzieinvancouver/wildhellgarden/blob/master/analyses/source/conceptualFigure.R) (lines 16-19) refer to, but I think they are not too relevant to making the figure:
```
 early<-filter(goo19,doy %in% c(115:240))
  early$GDD_10<-early$GDD_10-early$GDD_10[1]
  240-115
  142-115 #27 day diff
  253-240 #13
  27-13
```

**Comment by dbuona** [comment]
@DeirdreLoughnan thanks for doing this. I think those numbers in the conceptual figure plotting were just scratch for me to figure out which case study individuals could be used to illustrate the point in the figure. I think we're good, so I  am going to close this issue now.
